Python string to fstring 1333
SFTtech/openage pull request #1339
Opened 2020-11-24 14:07 UTC by TobiasFP

Converted A LOT of strings to python3.6 fstrings

2020-11-24 22:47 UTC, heinezen requested changes
Most things look good to me :)

Copyright dates (see kevin CI's output) for some files need to be fixed. Also, I think flynt skipped the Cython files? Would be good if you can check the `.pyx` files manually.

2020-11-24 22:47 UTC, heinezen commented on openage/convert/entity_object/export/formats/nyan_file.py
> +            output_str += f" as {alias}\n"
Not a flynt problem, but it would have been better to use join here :D Shame on me

2020-11-24 22:47 UTC, heinezen commented on buildsystem/codecompliance/__main__.py
> +
Trailing whitespce

2020-11-28 21:47 UTC, TobiasFP commented
Sadly, I have to dedicate all my time on a big project for the coming week. Wil get back to it on friday propably. Sorry.

2020-11-30 19:37 UTC, heinezen commented
@TobiasFP No problem

2020-12-07 17:31 UTC, TobiasFP commented
I will leave cython strings that include:
%%s & %#x 
as I have no idea how to convert to f-strings.

2020-12-08 05:01 UTC, heinezen commented
@TobiasFP 

`%#x` is telling Python to use hexadecimal notation. The `#` is used to put `0x` in front of the hex value. `x` denotes lowercase hex. You can achieve the same with f-strings by writing `{val:#x}`.

```
> "%#x" % 144
'0x90'
> f"{144:#x}"
'0x90'
```

%%s is a dirty hack that you can remove. It is used to evaluate the percent string twice. The first `%` escapes the second `%` so that it is treated as an actual char.

```
> "%%s is a %s" % "fruit"
'%s is a fruit'
> val = 1
> ("%%s is a %s" % "fruit") % ("apple" if val > 0 else "orange")
'apple is a fruit'
```

You can usually remove those by integrating the expression into the f string like this:

```
> f"{'apple' if val > 0 else 'orange'} is a {'fruit'}"
'apple is a fruit'
```

2020-12-13 19:10 UTC, heinezen commented
@TobiasFP Will you be able to finish this next week? :) It blocks other converter issues right now.

2020-12-13 22:44 UTC, TobiasFP commented
@heinezen I am sorry for not getting back sooner. There was actually a (corona) death in the semi-near family, so I had to put everything on hold for a couple days.
I have fixed everything up now as far as I can with the time I have available now.  I will not have any more time for the next two weeks, so I am very sorry if this leaves you in a rot, but  that is sadly the state of it.
I look forward to getting back to openage in a couple weeks time, and if this has not been fixed at that time, I will jump straight on it.
If it has been fixed, then I will hopefully manage to figure out the dds->png converter issue.
Again, sorry if this leaves you in a poor place, I hope my contribution has been helpful rather than problematic.

2020-12-13 22:45 UTC, TobiasFP commented
Oh and regarding what I have done:
Most things look good to me :)
I have fixed cython files, but missing copyright dates.

2020-12-14 14:41 UTC, heinezen approved these changes

2020-12-14 14:48 UTC, heinezen commented
Thank you. I have fixed a minor error + the copyright dates myself and pushed them to your PR :) Your contribution was very helpful. Looking forward to DDS->PNG when you get to it. 

And sorry for your loss. Hopefully everything gets better soon.

2020-12-14 14:49 UTC, merged