More informative KeyError messages in converter
SFTtech/openage pull request #1345
Opened 2020-12-19 16:55 UTC by Ayxan13

Added a try...catch to `get_member(self, name)` method of `ConverterObject`.

2020-12-19 20:32 UTC, heinezen commented
Nice ty

2020-12-19 20:32 UTC, heinezen approved these changes

2020-12-20 05:40 UTC, heinezen requested changes

2020-12-20 05:40 UTC, heinezen commented on openage/convert/entity_object/conversion/converter_object.py
> +            raise KeyError(f"{self} has no attribute: {key}") from err
change `{key}` to `{name}` pls

2020-12-20 05:43 UTC, heinezen commented
And you need to put your name + mail in `copying.md`

2020-12-20 06:24 UTC, Ayxan13 commented on openage/convert/entity_object/conversion/converter_object.py
> +            raise KeyError(f"{self} has no attribute: {key}") from err
Fixed it. Thank you for the catch!

2020-12-20 10:32 UTC, heinezen approved these changes

2020-12-20 10:33 UTC, merged

2020-12-20 10:33 UTC, heinezen commented
Merged!