Build instructions for Debian 12 issues
SFTtech/openage pull request #1548
Opened 2023-09-20 10:00 UTC by mantador

2023-09-20 10:07 UTC, okias commented
I would recommend rather to fix the build-system paths to look in the right place :)

2023-09-20 11:24 UTC, mantador commented
Would be nice but honestly I don't know cmake well enough. Also according to an old conversation with @heinezen on the matrix channel, seems to be a Debian-only issue.

2023-09-20 11:35 UTC, heinezen requested changes

2023-09-20 11:35 UTC, heinezen commented on doc/building.md
> +      - `./configure <your configure opts> -- -DCMAKE_PREFIX_PATH=/usr -DSDL2_DIR=/usr/include/SDL2` (you can use `find` to look for the correct paths)
Could you put this into the troubleshooting file instead? :)

https://github.com/SFTtech/openage/blob/master/doc/troubleshooting.md

2023-09-21 22:44 UTC, heinezen approved these changes

2023-09-23 07:29 UTC, merged