Neutralize remaining instances of gendered language
SFTtech/openage pull request #1590
Opened 2023-10-23 21:37 UTC by leetfin

2023-10-24 01:10 UTC, heinezen requested changes
That should work. There's just one thing that you'd need to change.

Also, you need to add your info to https://github.com/SFTtech/openage/blob/master/copying.md

2023-10-24 01:10 UTC, heinezen commented on doc/nyan/api_reference/reference_resistance.md
> +Condition which they must fulfill to make the resource spot harvestable.
I think that's just a typo and should say "be fulfilled" :D

2023-10-24 15:41 UTC, leetfin commented
Do I really need to be added to the authors? This seems like such a small change.

2023-10-25 08:15 UTC, TheJJ approved these changes

2023-10-25 08:16 UTC, TheJJ commented
it's fine, it's not a code contribution :)

2023-10-25 08:16 UTC, merged