Added custom resolution size for main and game
SFTtech/openage pull request #1672
Opened 2024-08-20 21:26 UTC by RaulGalvez288

Partial fix: #1546 

Implemented width and height parameters for main and game start modes.

Still have to add vsync and window modes.

2024-08-20 23:29 UTC, RaulGalvez288 commented
I keep getting some warnings for the Copyright year. Would I be able to change this? Wanted to ask in case its legal stuff.

![image](https://github.com/user-attachments/assets/3aa9fdb0-1569-4e68-8b89-57de521ee432)

2024-08-21 17:31 UTC, heinezen requested changes
Hey thank you so much! I can already give you some feedback on the work you've done.

2024-08-21 17:31 UTC, heinezen commented on libopenage/engine/engine.cpp
> +			   int wHeight) :
We use snake case for variable names, so `window_width` or just `width` are better.

2024-08-21 17:31 UTC, heinezen commented on libopenage/engine/engine.cpp
> +			   int wHeight) :
Also, you can use `size_t` instead of `int` for the type because the width/height shouldn't be negative.

2024-08-21 17:31 UTC, heinezen commented on libopenage/engine/engine.cpp
>  		this->threads.emplace_back([&, debug_graphics]() {
If you change the captured arguments to `[&, debug_graphics, wWidth, wHeight]`, you don't need to store width and height as members in `Engine`. You can just pass them through in the function.

2024-08-21 17:31 UTC, heinezen commented on openage/game/main_cpp.pyx
> +            args_cpp.height = 768
Instead of checking for `None`, you could also just set the `default` argument for the respective args to the default values.

2024-08-21 17:31 UTC, heinezen commented on openage/main/main_cpp.pyx
> +            args_cpp.height = 768
same here

2024-08-21 17:51 UTC, RaulGalvez288 commented
I did want to ask if changing the engine.cpp and engine.h was alright for this issue? or if I should just use Window::render like #1553

2024-08-21 18:44 UTC, heinezen commented
@RaulGalvez288 There is https://github.com/SFTtech/openage/blob/d09adb0901b15deb1b02b257ff437a283f694771/libopenage/renderer/window.h#L27-L38 if you want to use that.

2024-10-22 03:05 UTC, heinezen commented
@RaulGalvez288 Are you planning to continue working on this feature?

2024-12-02 23:19 UTC, closed without merging