Add is_complete() to UniformInput and Implement Checks in Demos
SFTtech/openage pull request #1718
Opened 2024-11-28 01:18 UTC by ZzzhHe

Hi, This is my first PR! Issue #1681 

This PR introduces a virtual is_complete() method to UniformInput, with an override in GlUniformInput to validate that all required uniform values are set. 

I'm currently a bit unsure about the optimal place to call is_complete() in the demos. Here are the options I'm considering:
+ After Creation by `new_uniform_input()`:  Might miss uniforms that are added later using the update() method.
+ After Every `update()`: This could introduce unnecessary overhead, especially if updates occur frequently.
+ Before Rendering: Might not catch updates made inside the rendering loop.

I'm looking forward to any feedback!

2024-11-29 07:41 UTC, C3pa commented on libopenage/renderer/opengl/uniform_input.cpp
> +
It looks like this file uses tabs for indenting, while your additions use 2 spaces.

2024-11-29 08:13 UTC, TheJJ requested changes
the duplication in each demo/usage to check for the errors should be optimized away, it would be better to check at a place all of them invoke anyway.

2024-11-30 14:25 UTC, heinezen requested changes
Very nice! I recommend you use `clang-format` on all files to solve your style issues.

2024-11-30 14:25 UTC, heinezen commented on libopenage/renderer/demo/demo_0.cpp
> +	if (!check_uniform_completeness({display_stuff})) {
Instead of `!`, `&&`, and `||` we usually use `not`, `and`, and `or`, since they are more readable :)

2024-11-30 14:25 UTC, heinezen commented on libopenage/renderer/demo/demo_0.cpp
> +#include "renderer/demo/util.h"
Have you added autoformatting with `clang-format` to your editor? The imports should be sorted alphabetically if you use `clang-format`.

2024-11-30 14:25 UTC, heinezen commented on libopenage/renderer/demo/util.cpp
> +	return all_complete;
You don't need `all_complete` if you short circuit in the if clause:

```suggestion
	// Iterate over each renderable object
	for (const auto &renderable : renderables) {
		if (renderable.uniform and not renderable.uniform->is_complete()) {
			return false;
		}
	}

	return true;
```

2024-11-30 14:25 UTC, heinezen commented on libopenage/renderer/demo/util.h
> +#include "renderer/renderable.h"
Small nitpick but you should add a space between external imports from the standard library and internal import from openage.

```suggestion
#include <vector>

#include "renderer/renderable.h"
```

2024-11-30 14:25 UTC, heinezen commented on libopenage/renderer/util.cpp
This file did not actually change, so the date should also not be changed.

2024-11-30 14:25 UTC, heinezen commented on libopenage/renderer/util.h
same here

2024-11-30 16:27 UTC, ZzzhHe commented
> Very nice! I recommend you use `clang-format` on all files to solve your style issues.

Thanks! I’ve formatted the files with clang-format. Also, I used a rebase to remove the two files that didn’t need changes, so I had to force-push.

2024-11-30 16:33 UTC, ZzzhHe commented
BTW, I noticed some code in the demo files is still using `!` instead of `not`. Should I go ahead and change that?

2024-11-30 16:48 UTC, heinezen commented
@ZzzhHe yes please :)

2024-11-30 20:39 UTC, ZzzhHe commented
> @ZzzhHe yes please :)

done.

2024-11-30 21:01 UTC, TheJJ requested changes
i think there's a better way to place the completeness check - in the renderer when a render pass is created.

2024-11-30 21:18 UTC, heinezen commented
@TheJJ It should not be done in the renderer itself because we might get a bunch problems. We would no longer be able to make partial uniform updates for shaders. Also, the uniforms may not be initialized when the render pass is created. Uniform initialization should be deferrable for optimization purposes, so that we can create a bunch of render objects without waiting for updates from the gamestate.

I actually just wanted this function for debugging because uninitialized uniform values are really hard to detect :D But they are not necessary for the general workflow I think.

2024-12-03 03:37 UTC, heinezen submitted a review, later dismissed

2024-12-03 03:37 UTC, heinezen commented on libopenage/renderer/demo/util.cpp
> +		if (renderable.uniform && not renderable.uniform->is_complete()) {
```suggestion
		if (renderable.uniform and not renderable.uniform->is_complete()) {
```

2024-12-03 03:42 UTC, heinezen approved these changes

2024-12-03 03:45 UTC, merged