Bind empty VAO to bufferless quad rendering
SFTtech/openage pull request #1734
Opened 2024-12-27 16:17 UTC by ZzzhHe

Hey! 👋 

I've made some initial fixes for the bufferless quad VAO issue, but wanted to get some advice before finalizing:

1. I tested my current code and noticed the VAO error was still there but occurred during shader validation in [`GlShaderProgram::use()`](https://github.com/SFTtech/openage/blob/beb894520e552cb6224cdd2f64697b2cf6e4ad8a/libopenage/renderer/opengl/shader_program.cpp#L295C1-L302C3). 

    This happens during `program->update_uniforms(in);` before `geom->draw()`; in `GlRenderer::render()`.

3. My current fix is binding the empty VAO in `geometry.cpp`, but I'm wondering:
  - Should we bind VAO before shader program validation?
  - Or should we handle/modify the validation error check in `GlShaderProgram::use()`?

Would appreciate your thoughts on the best approach here!

2024-12-31 21:30 UTC, heinezen commented
Hey thanks a lot!

I read through this while on the train today, so I have not tried the code out yet. But here are my thoughts on the approach:

Defining `quad_vao` for every `GlGeometry` class is likely too much as the member is useless for anything that is not a bufferless quad. Usually having `std::optional` variables is not a problem, but the game will instance a lot of `GlGeometry` objects over its runtime. Also, OpenGL only allows a certain number of vertex arrays to be defined I think. So it's worth to think about a better solution here.

Making the VAO `static` would be nice, but since we need the OpenGL context I doubt it's possible. I think the least dirty solution would be:

1. Create a single VAO somewhere else (probably in the `GlRenderer` initialization)
2. Bind it at the start of every `render(..)` call
3. Keep the code in `GlGeometry` as-is, except for making a comment that a VAO needs to be bound in the switch statement branch for bufferless quad.

This ensures that a VAO is always bound during rendering and should also be much more storage/runtime efficient.

2024-12-31 21:32 UTC, heinezen commented
> I tested my current code and noticed the VAO error was still there but occurred during shader validation in [GlShaderProgram::use()](https://github.com/SFTtech/openage/blob/beb894520e552cb6224cdd2f64697b2cf6e4ad8a/libopenage/renderer/opengl/shader_program.cpp#L295C1-L302C3).
>
> This happens during program->update_uniforms(in); before geom->draw(); in GlRenderer::render().

This is normal btw ;) OpenGL does not raise errors because they happen on the GPU. Hence, we only learn about them during validity checks when we explicitly request the error state.

2025-01-01 15:33 UTC, ZzzhHe commented
Got it, thanks! Working on the updates now.

2025-01-01 23:40 UTC, heinezen requested changes

2025-01-01 23:40 UTC, heinezen commented on libopenage/renderer/opengl/geometry.h
Since there are no changes here anymore, the date change is also unnecessary ;)

2025-01-01 23:40 UTC, heinezen commented on libopenage/renderer/opengl/geometry.cpp
> +		// a VAO must be bound before this call. This is handled by GlRenderer.
references to other classes outdated quickly when the code is refactored. Better just state what needs to happen.

```suggestion
		// any VAO must be bound before this call
```

2025-01-01 23:40 UTC, heinezen commented on libopenage/renderer/opengl/renderer.h
> +	std::shared_ptr<GlVertexArray> shared_quad_vao;
You can make this member a `unique_ptr` I think, since it's only used by the GlRenderer class.

2025-01-01 23:40 UTC, heinezen commented on libopenage/renderer/opengl/renderer.cpp
> +	shared_quad_vao(std::make_shared<GlVertexArray>(ctx)) {
You should use a curly braced-initializer here and wherever possible. This prevents unintended type conversion.

2025-01-01 23:40 UTC, heinezen commented on libopenage/renderer/opengl/renderer.cpp
> +	// bind the shared quad vao for all bufferless quad geometries
I slightly reworded the comment so that it's more clear what's happening.

```suggestion
	// ensure that an (empty) VAO is bound before rendering geometry
	// a bound VAO is required to render bufferless quad geometries by OpenGL
	// see https://www.khronos.org/opengl/wiki/Vertex_Rendering#Causes_of_rendering_failure
```

2025-01-01 23:40 UTC, heinezen commented on libopenage/renderer/opengl/renderer.h
> +	std::shared_ptr<GlVertexArray> shared_quad_vao;
```suggestion
    /// An empty vertex array object (VAO).
    ///
    /// This VAO has to be bound at the start of a render pass to ensure
    /// that bufferless quad geometry can be drawn without errors. Drawing a
    /// bufferless quad requires any VAO to be bound
    /// see https://www.khronos.org/opengl/wiki/Vertex_Rendering#Causes_of_rendering_failure
	std::shared_ptr<GlVertexArray> shared_quad_vao;
```

2025-01-02 16:03 UTC, ZzzhHe commented on libopenage/renderer/opengl/renderer.h
> +	std::shared_ptr<GlVertexArray> shared_quad_vao;
I attempted to use `unique_ptr`, but encountered an issue since it requires the complete type definition. When I moved the include to the header file to replace forward declaration, it led to circular include dependencies. Did I do something wrong, or should I dive into the dependency cycle to fix it?

2025-01-02 19:31 UTC, heinezen commented on libopenage/renderer/opengl/renderer.h
> +	std::shared_ptr<GlVertexArray> shared_quad_vao;
No, you are right. I think you can change it back to `shared_ptr`.

I think the problem here is that `unique_ptr` only allows incomplete types under specific circumstances. I also didn't know the specifics for that :'D

> std::unique_ptr may be constructed for an [incomplete type](https://en.cppreference.com/w/cpp/language/incomplete_type) T, such as to facilitate the use as a handle in the [pImpl idiom](https://en.cppreference.com/w/cpp/language/pimpl). If the default deleter is used, T must be complete at the point in code where the deleter is invoked, which happens in the destructor, move assignment operator, and reset member function of std::unique_ptr. (In contrast, [std::shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr) can't be constructed from a raw pointer to incomplete type, but can be destroyed where T is incomplete). Note that if T is a class template specialization, use of unique_ptr as an operand, e.g. !p requires T's parameters to be complete due to [ADL](https://en.cppreference.com/w/cpp/language/adl).

https://en.cppreference.com/w/cpp/memory/unique_ptr

2025-01-02 19:44 UTC, ZzzhHe commented on libopenage/renderer/opengl/renderer.h
> +	std::shared_ptr<GlVertexArray> shared_quad_vao;
Thanks, I will change it back

2025-01-02 22:07 UTC, heinezen approved these changes

2025-01-02 22:07 UTC, heinezen commented
Very good!

2025-01-02 22:07 UTC, merged